const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C6EFA",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f9f9f9",
    cardForeground: "#0a0a0a",
    primary: "#7C6EFA",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#f0f0f0",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#7C6EFA",
    background: "#0D0D0F",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#7C6EFA",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#EBEBF5",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#2C2C2E",
    accentForeground: "#EBEBF5",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#2C2C2E",
    input: "#1C1C1E",
  },
  radius: 14,
};

export default colors;
